project:
  type: website
  output-dir: docs

website:
  site-url: "https://jyovika.github.io/jyovika-analytics-portfolio/"
  site-path: "/"
  title: "Jyovika Aswale"
  description: "Blog + portfolio with R analysis, visualisation, modelling and reproducible data work."
  navbar:
    left:
      - text: "Home"
        href: about.qmd
      - text: "Blogs"
        href: index.qmd
    right:
      - icon: github
        href: https://github.com/jyovika
  page-footer:
    left: "Â© 2025 Jyovika Aswale"
    right: "Built with Quarto"

format:
  html:
    theme: flatly
    css: [styles.css]
    toc: true
    smooth-scroll: true
    anchor-sections: true
    sitemap: true        
    rss: true          
    open-graph: true    
    twitter-card: true 
    include-in-header: "_meta.html"
